apiVersion: apps/v1
kind: Deployment
metadata:
  name: precio-deployment
  labels:
    app: precio-deployment
spec:
  selector:
    matchLabels:
      app: precio-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: precio-deployment
    spec:
      containers:
        - name: precio
          image: cosiobit/precio
          ports:
            - containerPort: 8091
          env:
            - name: SERVER_PORT
              value: "0"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_HOST_PRECIO
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_PORT_PRECIO
            - name: DB_DBNAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_DBNAME_PRECIO
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_USER_PRECIO
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_PASSWORD_PRECIO