apiVersion: v1
kind: PersistentVolume
metadata:
  name: reparaciondb-pv
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/reparaciondb-data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: reparaciondb-pvc
  labels:
    app: postgres
    tier: database
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reparaciondb-deployment
  labels:
    app: reparaciondb-deployment
    tier: database
spec:
  selector:
    matchLabels:
      app: reparaciondb-deployment
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: reparaciondb-deployment
        tier: database
    spec:
      containers:
        - name: reparaciondb
          image: postgres
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_USER_REPARACION
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_PASSWORD_REPARACION
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: reparaciondb-data # This should match the volume name below
      volumes:
        - name: reparaciondb-data # This should match the volume mount name above
          persistentVolumeClaim:
            claimName: reparaciondb-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: reparaciondb-service
  labels:
    app: reparaciondb-service
    tier: database
spec:
  ports:
    - port: 5434
      targetPort: 5432
      protocol: TCP
  selector:
    app: reparaciondb-deployment
    tier: database
  type: LoadBalancer
