apiVersion: apps/v1
kind: Deployment
metadata:
  name: reparacion-deployment
  labels:
    app: reparacion-deployment
spec:
  selector:
    matchLabels:
      app: reparacion-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: reparacion-deployment
    spec:
      containers:
        - name: reparacion
          image: cosiobit/reparacion
          ports:
            - containerPort: 8092
          env:
            - name: SERVER_PORT
              value: "0"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_HOST_REPARACION
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_PORT_REPARACION
            - name: DB_DBNAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_DBNAME_REPARACION
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_USER_REPARACION
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_PASSWORD_REPARACION