apiVersion: apps/v1
kind: Deployment
metadata:
  name: vehiculo-deployment
  labels:
    app: vehiculo-deployment
spec:
  selector:
    matchLabels:
      app: vehiculo-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: vehiculo-deployment
    spec:
      containers:
        - name: vehiculo
          image: cosiobit/vehiculo
          ports:
            - containerPort: 8093
          env:
            - name: SERVER_PORT
              value: "0"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_HOST_VEHICULO
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_PORT_VEHICULO
            - name: DB_DBNAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_DBNAME_VEHICULO
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_USER_VEHICULO
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_PASSWORD_VEHICULO