apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config-map
  labels:
    app: postgres-config-map
data:
  POSTGRES_DB_HOST: postgres
  #base de dato Cuotas
  POSTGRES_DB_MARCA: proyect2marca
  #base de dato Estudiantes
  POSTGRES_DB_REPARACION: proyect2reparacion
  #base de dato Estudiantes
  POSTGRES_DB_VEHICULO: proyect2vehiculo